services:
  open-webui:
    env_file: .env
    container_name: mcp-postgresql-ops-open-webui
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "${DOCKER_EXTERNAL_PORT_OPENWEBUI}:8080"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - open-webui-data:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  mcp-server:
    env_file: .env
    container_name: mcp-postgresql-ops-mcp-server
    image: call518/mcp-server-postgresql-ops:1.0.0
    ports:
      - "${DOCKER_EXTERNAL_PORT_MCP_SERVER}:8000" ### (WARNING) Must be same with port number of 'FASTMCP_PORT', 'mcp-config.json' and 'mcp-config.json.http'
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./.env:/app/.env:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8000 && sleep 5"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  mcpo-proxy:
    env_file: .env
    image: call518/mcpo-proxy-postgresql-ops:1.0.2
    container_name: mcp-postgresql-ops-mcpo-proxy
    depends_on:
      mcp-server:
        condition: service_healthy
    ports:
      - "${DOCKER_EXTERNAL_PORT_MCPO_PROXY}:8000"
    volumes:
      - ./mcp-config.json.http:/app/config/mcp-config.json
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  open-webui-data:
    name: open-webui-data-mcp-postgresql-ops
  postgresql-data:
    name: postgresql-data-mcp-postgresql-ops
